"""initial afterlook schema

Revision ID: ad58a4b4eef7
Revises:
Create Date: 2026-09-16 17:51:59.157086

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad58a4b4eef7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clientes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("email_google", sa.String(length=254), nullable=False),
        sa.Column("telefono", sa.String(length=30), nullable=True),
        sa.Column("whatsapp", sa.String(length=30), nullable=True),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("estado_cuenta", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado_cuenta IN ('ACTIVA', 'SUSPENDIDA', 'INACTIVA')",
            name="ck_clientes_estado_cuenta",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_google"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=30), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "servicios",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("tipo_servicio", sa.String(length=30), nullable=False),
        sa.Column("duracion_minutos", sa.Integer(), nullable=False),
        sa.Column("precio_base", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tipo_servicio IN ('BARBERIA', 'PELUQUERIA')",
            name="ck_servicios_tipo_servicio",
        ),
        sa.CheckConstraint(
            "duracion_minutos > 0", name="ck_servicios_duracion_positiva"
        ),
        sa.CheckConstraint("precio_base >= 0", name="ck_servicios_precio_no_negativo"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nombre_completo", sa.String(length=150), nullable=False),
        sa.Column("email_google", sa.String(length=254), nullable=False),
        sa.Column("rol_id", sa.BigInteger(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["rol_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_google"),
    )
    op.create_table(
        "auditoria_cambios",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entidad_tipo", sa.String(length=40), nullable=False),
        sa.Column("entidad_id", sa.BigInteger(), nullable=False),
        sa.Column("accion", sa.String(length=30), nullable=False),
        sa.Column("datos_anteriores", sa.JSON(), nullable=True),
        sa.Column("datos_nuevos", sa.JSON(), nullable=True),
        sa.Column("realizado_por_usuario_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "fecha",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["realizado_por_usuario_id"], ["usuarios.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_auditoria_entidad",
        "auditoria_cambios",
        ["entidad_tipo", "entidad_id"],
        unique=False,
    )
    op.create_table(
        "disponibilidades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("dia_semana", sa.Integer(), nullable=False),
        sa.Column("hora_desde", sa.Time(), nullable=False),
        sa.Column("hora_hasta", sa.Time(), nullable=False),
        sa.Column("bloqueo_excepcional", sa.Boolean(), nullable=False),
        sa.Column("motivo", sa.String(length=255), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dia_semana BETWEEN 1 AND 7", name="ck_disponibilidades_dia"
        ),
        sa.CheckConstraint(
            "hora_hasta > hora_desde", name="ck_disponibilidades_rango_horario"
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_disponibilidades_usuario_dia",
        "disponibilidades",
        ["usuario_id", "dia_semana"],
        unique=False,
    )
    op.create_table(
        "reservas",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=False),
        sa.Column("servicio_id", sa.BigInteger(), nullable=False),
        sa.Column("peluquero_id", sa.BigInteger(), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=True),
        sa.Column("fecha_inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duracion_minutos", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("canal_reserva", sa.String(length=20), nullable=False),
        sa.Column("precio_estimado", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notas_cliente", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "canal_reserva IN ('WEB', 'ADMIN', 'TELEFONO', 'WHATSAPP')",
            name="ck_reservas_canal",
        ),
        sa.CheckConstraint(
            "estado IN ('PENDIENTE', 'EN_ESPERA', 'AGENDADA', 'RESERVADA', 'CONFIRMADA', 'ASISTIO', 'NO_ASISTIO', 'CANCELADA')",
            name="ck_reservas_estado",
        ),
        sa.CheckConstraint(
            "duracion_minutos > 0", name="ck_reservas_duracion_positiva"
        ),
        sa.CheckConstraint(
            "precio_estimado >= 0", name="ck_reservas_precio_no_negativo"
        ),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["peluquero_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["servicio_id"], ["servicios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reservas_agenda_peluquero_fecha",
        "reservas",
        ["peluquero_id", "fecha_inicio"],
        unique=False,
    )
    op.create_index(
        "ix_reservas_cliente_fecha",
        "reservas",
        ["cliente_id", "fecha_inicio"],
        unique=False,
    )
    op.create_table(
        "usuarios_servicios",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("servicio_id", sa.BigInteger(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["servicio_id"], ["servicios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("usuario_id", "servicio_id", name="uq_usuario_servicio"),
    )
    op.create_table(
        "eventos_calendario",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("reserva_id", sa.BigInteger(), nullable=False),
        sa.Column("proveedor", sa.String(length=30), nullable=False),
        sa.Column("evento_externo_id", sa.String(length=255), nullable=True),
        sa.Column("estado_sync", sa.String(length=20), nullable=False),
        sa.Column("ultima_sincronizacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detalle_error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "estado_sync IN ('PENDIENTE', 'SINCRONIZADO', 'FALLIDO', 'CANCELADO')",
            name="ck_eventos_calendario_estado_sync",
        ),
        sa.ForeignKeyConstraint(["reserva_id"], ["reservas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "reserva_id", "proveedor", name="uq_evento_calendario_reserva_proveedor"
        ),
    )
    op.create_table(
        "historial_reservas",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("reserva_id", sa.BigInteger(), nullable=False),
        sa.Column("estado_anterior", sa.String(length=20), nullable=True),
        sa.Column("estado_nuevo", sa.String(length=20), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column("realizado_por_usuario_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "fecha",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["realizado_por_usuario_id"], ["usuarios.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["reserva_id"], ["reservas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notificaciones",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("reserva_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("canal", sa.String(length=20), nullable=False),
        sa.Column("destinatario", sa.String(length=254), nullable=False),
        sa.Column("estado_envio", sa.String(length=20), nullable=False),
        sa.Column("fecha_programada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fecha_envio", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "canal IN ('EMAIL', 'WHATSAPP', 'SMS')", name="ck_notificaciones_canal"
        ),
        sa.CheckConstraint(
            "estado_envio IN ('PENDIENTE', 'ENVIADA', 'FALLIDA')",
            name="ck_notificaciones_estado_envio",
        ),
        sa.ForeignKeyConstraint(["reserva_id"], ["reservas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notificaciones_pendientes",
        "notificaciones",
        ["estado_envio", "fecha_programada"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notificaciones_pendientes", table_name="notificaciones")
    op.drop_table("notificaciones")
    op.drop_table("historial_reservas")
    op.drop_table("eventos_calendario")
    op.drop_table("usuarios_servicios")
    op.drop_index("ix_reservas_cliente_fecha", table_name="reservas")
    op.drop_index("ix_reservas_agenda_peluquero_fecha", table_name="reservas")
    op.drop_table("reservas")
    op.drop_index("ix_disponibilidades_usuario_dia", table_name="disponibilidades")
    op.drop_table("disponibilidades")
    op.drop_index("ix_auditoria_entidad", table_name="auditoria_cambios")
    op.drop_table("auditoria_cambios")
    op.drop_table("usuarios")
    op.drop_table("servicios")
    op.drop_table("roles")
    op.drop_table("clientes")
    # ### end Alembic commands ###
